#pragma config(Sensor, S1,     ,               sensorLightActive)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int grey = 33;

task main()
{
	int left = 0;
	int right = 0;
	int cc = 20;
	int max = 80;
	while(true)
	{
		if(SensorValue[S1] > grey)
		{
			left += cc;
			if(left > max) left = max;
			right = 0;
			motor[motorB] = 100;
			motor[motorC] = 100 - left;
		}
		else
		{
			right += cc;
			if(right > max) right = max;
			left = 0;
			motor[motorB] = 100 - right;
			motor[motorC] = 100;
		}
		wait1Msec(1);
	}


}
