AGRPARSE_DIR		:= ./dumbParser
INCLUDE_FLAGS		:= -I$(AGRPARSE_DIR)
CXX					:= g++
SPECIAL_FLAGS		:= -std=c++11


all:
	$(CXX) main.cpp $(AGRPARSE_DIR)/dumbParser.cpp -o sockets $(INCLUDE_FLAGS) $(SPECIAL_FLAGS) -g3

