#pragma config(Sensor, S1,     ,               sensorLightActive)
#pragma config(Sensor, S2,     ,               sensorLightActive)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


void killJar();

const int motorLeftIndex = motorB;
const int motorRightIndex = motorC;

const int sensorLightIndex_right = S1;
const int sensorLightIndex_left = S2;

bool crossDetected = 0;

int getSensor();
//int speed;
//int rudder;

int motorLeft;
int motorRight;

int grey_left;
int grey_right;

int initialError;

void setOutputOnMotors(int l, int r);
void movenment_init();
void go(int desiredSpeed, int desiredTurn);

int max(int x, int y){
	if(x > y)	return x;
	return y;
}

int min(int x, int y){
	if(x < y)	return x;
	return y;
}

void setOutputOnMotors(int l, int r){
	if(abs(l) > 100){
		l = 100 * l / abs(l);
	}
	if(abs(r) > 100){
		r = 100 * r / abs(r);
	}
	motor[motorLeftIndex] = l;
	motor[motorRightIndex] = r;
}


void movenment_init(){
	grey_left = SensorValue[sensorLightIndex_left] - 10;
	grey_right = SensorValue[sensorLightIndex_right] - 10;
	initialError = getSensor();
	setOutputOnMotors(0, 0)	;
}

int rudderOfTurn(int desiredSpeed, int desiredTurn){
	int res = (int)( (float)desiredTurn / 5);
	return res;
}

void go(int desiredSpeed, int desiredTurn){
	int rudder = rudderOfTurn(desiredSpeed, desiredTurn);
	int speed = desiredSpeed;
	motorLeft = speed + rudder;
	motorRight = speed - rudder;

	setOutputOnMotors(motorLeft, motorRight);
}




float coeff = 40;
float diffCoeff = 30;
float cubeCoeff = 0.03;
// float diffCoeff = 300;
// float cubeCoeff = 0.3;

// int grey = 30;

int baseSpeed = 100;
int maxSpeed = 100;

float curSpeed = baseSpeed;

int curSensor;
int oldSensor;

int leftSide = 1;



int propRegulator(){
	return (int)( coeff * (curSensor) );
}

int diffRegulator(){
	return diffCoeff * (curSensor - oldSensor);
}

int cubeRegulator(){
	int diff = (curSensor);
	return cubeCoeff * diff * diff * diff;
}

int currentEncoder;
int currentEncoderDelta;
const int currentEncoderDeltaBorder = 100;
const int encoderBorder = 400;
bool goCountingEncoders = 0;
//int summingCorrection;
//const int summingCorrectionBorder = 200;


void recountEncoder(){
	currentEncoder = (nMotorEncoder[motorRightIndex] + nMotorEncoder[motorLeftIndex]);
	currentEncoderDelta = (nMotorEncoder[motorRightIndex] - nMotorEncoder[motorLeftIndex]);
}

void treatCrossDetected(){
	nMotorEncoder[motorRightIndex] = 0;
	nMotorEncoder[motorLeftIndex] = 0;
	goCountingEncoders = true;
	currentEncoderDelta = 0;
	currentEncoder = 0;
}

bool distancePassed(){
	if(currentEncoder > encoderBorder){
		return true;
	}
	return false;
}

int getSensor(){
	int res = SensorValue[sensorLightIndex_left] - SensorValue[sensorLightIndex_right];
	return res;
}

int getSensorCorrectingError(){
	return getSensor() - initialError;
}

void makeActionCorner(){
	PlaySound(soundBeepBeep);
}

void makeAction(){
	PlaySound(soundDownwardTones);
}


task countCrosses(){
	ClearTimer(T1);

	int count = 0;


	while(1){
		if(
			(time1[T1] > 200) &&
			(SensorValue[sensorLightIndex_left] < grey_left) &&
			(SensorValue[sensorLightIndex_right] < grey_right)
		){
			count++;
			ClearTimer(T1);
			crossDetected = true;
			//PlaySound(soundBeepBeep);

		}
		wait1Msec(1);
	}
}

void stabilize(){

		for(int i = 0; i < 100; i++){
			oldSensor = curSensor;
			curSensor = getSensorCorrectingError();

			go(0, leftSide * propRegulator());

			nxtDisplayString(0, "stabilize");

			wait1Msec(1);
		}
		nxtDisplayString(0, "kill");
}

task main(){
	nMotorEncoder[motorRight] = 0;

	movenment_init();

	StartTask(countCrosses);

	while(1){

		oldSensor = curSensor;
		curSensor = getSensorCorrectingError();

		int discrapencyProportional = propRegulator();
		int discrapencyDifferential = diffRegulator();
		int discrapencyCube = cubeRegulator();

		int discrapency = discrapencyProportional + discrapencyDifferential + discrapencyCube;
		discrapency *= leftSide;

		//summingCorrection += discrapency;
		go(curSpeed, discrapency);
		nxtDisplayString(0, "go");

		recountEncoder();

		if(crossDetected){
			treatCrossDetected();
			crossDetected = false;
		}

		nxtDisplayString(1, "counting = %d", currentEncoder);
		nxtDisplayString(2, "discrap = %d", currentEncoderDelta);
		if(goCountingEncoders){
			if(distancePassed()){



				if(abs(currentEncoderDelta) > currentEncoderDeltaBorder){
					makeActionCorner();
				} else {
					//makeAction();

					stabilize();

					killJar();
				}

				goCountingEncoders = false;

			}
		}


		wait1Msec(1);
	}
}

void killJar(){
	nMotorEncoder[motorLeftIndex] = 0;
	int killSpead = 60;
	motor[motorLeftIndex] = -killSpead;
	motor[motorRightIndex] = killSpead;

  while (nMotorEncoder[motorLeftIndex]>-260){
  	wait1Msec(10);
  }

  nMotorEncoder[motorLeftIndex] = 0;
  motor[motorLeftIndex] = killSpead;
	motor[motorRightIndex] = killSpead;
  while (nMotorEncoder[motorLeftIndex]<250){
  		wait1Msec(10);
  }
   motor[motorLeftIndex] = -killSpead;
	motor[motorRightIndex] = -killSpead;
	while (nMotorEncoder[motorLeftIndex]>=0){
  		wait1Msec(10);
  }

  nMotorEncoder[motorLeftIndex] = 0;

  motor[motorLeftIndex] = killSpead;
	motor[motorRightIndex] = -killSpead;
  while (nMotorEncoder[motorLeftIndex]<260){
  	wait1Msec(10);
  }
  motor[motorLeftIndex] = 0;
	motor[motorRightIndex] = 0;
}
