#pragma config(Sensor, S1,     ,               sensorLightActive)
#pragma config(Sensor, S2,     ,               sensorTouch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

const int motorLeftIndex = motorB;
const int motorRightIndex = motorA;

int speed;
int rudder;

int motorLeft;
int motorRight;

void setOutputOnMotors(int l, int r);
void movenment_init();
void go(int desiredSpeed, int desiredTurn);

int max(int x, int y){
	if(x > y)	return x;
	return y;
}

int min(int x, int y){
	if(x < y)	return x;
	return y;
}

void setOutputOnMotors(int l, int r){
	if(abs(l) > 100){
		l = 100 * l / abs(l);
	}
	if(abs(r) > 100){
		r = 100 * r / abs(r);
	}
	motor[motorLeftIndex] = l;
	motor[motorRightIndex] = r;
}


void movenment_init(){
	motorLeft = 0;
	motorRight = 0;
	speed = 0;
	rudder = 0;
}

int rudderOfTurn(int desiredSpeed, int desiredTurn){
	int res = (int)( (float)desiredTurn / 5);
	return res;
}

void go(int desiredSpeed, int desiredTurn){
	rudder = rudderOfTurn(desiredSpeed, desiredTurn);
	speed = desiredSpeed;
	motorLeft = speed + rudder;
	motorRight = speed - rudder;

	setOutputOnMotors(motorLeft, motorRight);
}



float baseCoeff = 40;
float coeff = baseCoeff;

float baseDiffCoeff = 300;
float diffCoeff = baseDiffCoeff;

float baseCubeCoeff = 0.3;
float cubeCoeff = baseCubeCoeff;

int grey = 30;

int baseSpeed = 100;
int maxSpeed = 100;

float curSpeed = baseSpeed;

int curSensor;
int oldSensor;


void dynamicalAdjust(int discrapency){
	//coeff = baseCoeff * 2 * sqrt( curSpeed / maxSpeed );
	//curSpeed = maxSpeed * 20 / sqrt(abs(discrapency));
}



int propRegulator(){
	return (int)( coeff * (curSensor - grey) );
}

int diffRegulator(){
	return diffCoeff * (curSensor - oldSensor);
}

int cubeRegulator(){
	int diff = (curSensor - grey);
	return cubeCoeff * diff * diff * diff;
}

int leftSide = 1;

task main(){

	movenment_init();


	while(1){

		oldSensor = curSensor;
		curSensor = SensorValue[S1];

		int discrapencyProportional = propRegulator();
		int discrapencyDifferential = diffRegulator();
		int discrapencyCube = cubeRegulator();
		if(discrapencyCube < 0){
			//discrapencyCube = 0;
		}

		int discrapency = discrapencyProportional + discrapencyDifferential + discrapencyCube;

		/*
		if( (discrapencyDifferential > 0) && (discrapency > 0) ){
			leftSide = -1;
		}
		if( (discrapencyDifferential < 0) && (discrapency < 0) ){
			leftSide = 1;
		}
		*/

		discrapency *= leftSide;


		dynamicalAdjust(discrapency);

		go(curSpeed, discrapency);

		wait1Msec(1);
		//go(baseSpeed, 20);
	}
}
