#pragma config(Sensor, S3,     ,               sensorSONAR)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define motorLeft motorA
#define motorRight motorB
#define sonnarId S3

int basicDist;
int extremeMinimumDist = 20;
int getSonnarValue();
void getBasicValue();
void wallRide();
void setOutputOnMotors(int l, int r);
void showSensor();

const float prop_coeff = 2.0;
const float diff_coeff = 5.0;
const float basicSpeed = 50.0;
const float d = 10.0;

int oldDist;
const int deltaT = 1;

void getBasicValue(){
	oldDist = getSonnarValue();
	basicDist = getSonnarValue();
}
int getSonnarValue(){
	return SensorValue[sonnarId];
}

void setOutputOnMotors(int l, int r){
	motor[motorLeft] = l;
	motor[motorRight] = r;
}

void showSensor(){
	nxtDisplayTextLine(0, "sonnar = %d", getSonnarValue());
}
void showTypeOfOperation(string str){
	nxtDisplayTextLine(1, str);
}

void showCorrection(int cor){
	nxtDisplayTextLine(2, "corr = %d", cor);
}


void wallRide(){

	int currentDist = getSonnarValue();

	float prop_discrapency = currentDist - basicDist;
	float prop_correction = prop_discrapency * prop_coeff;

	float diff_discrapency = currentDist - oldDist;
	float diff_correction = diff_discrapency* diff_coeff;

	float correction;

	string strings[3] = {"extreme", "corner", "normal"};
	//const char* strings = "extreme";//, "corner", "normal"};
	int typeOfOperation;

	if( currentDist < extremeMinimumDist ){
		correction = prop_correction + diff_correction;
		setOutputOnMotors(correction, -correction);
		typeOfOperation = 0;
	} else if( currentDist > basicDist * 2 ){
		correction = basicSpeed * d / basicDist;
		oldDist = 2 * basicSpeed;
		setOutputOnMotors(basicSpeed + correction, basicSpeed - correction);
		typeOfOperation = 1;
	} else {

		correction = prop_correction + diff_correction;
		oldDist = currentDist;
		setOutputOnMotors(basicSpeed + correction, basicSpeed - correction);
		typeOfOperation = 2;
	}

	showTypeOfOperation(strings[typeOfOperation]);
	showCorrection(correction)


}


task main()
{
	getBasicValue();

	while(1){
		wallRide();
		showSensor();
		//setOutputOnMotors(0, 50);
		wait1Msec(deltaT);
	}


}
task main()
{



}
